"""Task information and progress summary models."""

from __future__ import annotations

from datetime import datetime

from handoff._utils import utc_now
from enum import Enum

from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    """Lifecycle states of a handoff task."""

    IN_PROGRESS = "in_progress"
    PAUSED = "paused"
    BLOCKED = "blocked"
    COMPLETED = "completed"
    FAILED = "failed"


class HandoffReason(str, Enum):
    """Reasons for triggering a context handoff."""

    TOKEN_LIMIT = "token_limit"
    TASK_DELEGATION = "task_delegation"
    ERROR_RECOVERY = "error_recovery"
    USER_TRIGGERED = "user_triggered"
    CAPABILITY_MISMATCH = "capability_mismatch"
    SCHEDULED = "scheduled"


class Priority(str, Enum):
    """Handoff priority levels."""

    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    CRITICAL = "critical"


class CheckpointRef(BaseModel):
    """Reference to a persisted checkpoint.

    Separates native framework checkpoints from custom/external ones so
    consumers know which adapter to use for recovery.
    """

    native_ref: str | None = Field(
        default=None,
        description="Framework-native checkpoint ID (e.g., LangGraph thread_id).",
    )
    custom_ref: str | None = Field(
        default=None,
        description="Custom/external checkpoint identifier.",
    )
    checkpoint_type: str = Field(
        default="unknown",
        description="Type identifier for the checkpoint store.",
    )


class ProgressSummary(BaseModel):
    """Structured progress summary generated by LLM or fallback rules.

    The summary should be concise enough to fit within a system prompt
    without consuming excessive token budget.
    """

    completed_steps: list[str] = Field(default_factory=list)
    current_step: str = Field(default="")
    key_intermediate_results: str = Field(default="")
    blockers: str = Field(default="")
    next_expected_action: str = Field(default="")
    generated_at: datetime = Field(default_factory=utc_now)
    generation_method: str = Field(
        default="llm",
        description="How this summary was produced: 'llm' or 'rule_based_fallback'.",
    )
    raw_summary: str = Field(
        default="",
        description="Original LLM output before structured parsing.",
    )

    def to_markdown(self) -> str:
        """Render as structured Markdown for system prompt injection."""
        lines = [
            "## 当前任务进度",
            "",
            f"- **已完成步骤**: {', '.join(self.completed_steps) if self.completed_steps else '无'}",
            f"- **当前步骤**: {self.current_step or '未明确'}",
            f"- **关键中间结果**: {self.key_intermediate_results or '无'}",
            f"- **遇到的问题/阻塞点**: {self.blockers or '无'}",
            f"- **预期下一步动作**: {self.next_expected_action or '未明确'}",
        ]
        return "\n".join(lines)


class TaskInfo(BaseModel):
    """Task description and execution state."""

    original_task_id: str = Field(description="Stable identifier for the logical task.")
    description: str = Field(description="Original task description text.")
    expected_output_format: str | None = Field(
        default=None,
        description="JSON Schema or structured description of expected output.",
    )
    status: TaskStatus = Field(default=TaskStatus.IN_PROGRESS)
    progress_summary: ProgressSummary = Field(default_factory=ProgressSummary)
    checkpoint_ref: CheckpointRef | None = Field(default=None)
    required_capabilities: list[str] = Field(
        default_factory=list,
        description="Capability tags required to continue this task.",
    )
